notifications:
  argocdUrl: ${argoUrl}
  notifiers:
    service.teams: |
      recipientUrls:
      %{~ for k, v in serviceTeamsChannels ~}
        ${k}: ${v}
      %{~ endfor ~}
    
    service.email.mail: |
      host: mail.example.com
      port: 25
      from: argocd@example.com
    
    service.webhook.github: |
      url: ${githubURL}
      headers:
      - name: Authorization
        value: token ${githubToken}

    service.slack: |
      token: ${slackToken}

  subscriptions:
    - recipients:
      %{~ for k, v in defaultRecipients ~}
        - ${k}:${v}
      %{~ endfor ~}
      
      triggers:
        - on-sync-succeeded
        - on-sync-status-unknown
        - on-sync-failed
        - on-health-degraded
        - on-deployed
        - on-deleted
        - on-created
        - on-sync-running
  
  triggers:
    trigger.on-deployed: |
      - description: Application is synced and healthy. Triggered once per commit.
        oncePer: app.status.sync.revision
        send:
        - app-deployed
        when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
    trigger.on-health-degraded: |
      - description: Application has degraded
        send:
        - app-health-degraded
        when: app.status.health.status == 'Degraded'
    trigger.on-sync-failed: |
      - description: Application syncing has failed
        send:
        - app-sync-failed
        when: app.status.operationState.phase in ['Error', 'Failed']
    trigger.on-sync-running: |
      - description: Application is being synced
        send:
        - app-sync-running
        when: app.status.operationState.phase in ['Running']
    trigger.on-sync-status-unknown: |
      - description: Application status is 'Unknown'
        send:
        - app-sync-status-unknown
        when: app.status.sync.status == 'Unknown'
    trigger.on-sync-succeeded: |
      - description: Application syncing has succeeded
        send:
        - app-sync-succeeded
        when: app.status.operationState.phase in ['Succeeded']
    
    defaultTriggers: |
      - on-sync-status-unknown
  
  templates:
    template.app-deployed: |
      email:
        subject: New version of an application {{.app.metadata.name}} is up and running.
      message: |
        {{if eq .serviceType "slack"}}:white_check_mark:{{end}} Application {{.app.metadata.name}} is now running new version of deployments manifests.
      slack:
        attachments: |
          [{
            "title": "{{ .app.metadata.name}}",
            "title_link":"{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
            "color": "#18be52",
            "fields": [
            {
              "title": "Sync Status",
              "value": "{{.app.status.sync.status}}",
              "short": true
            },
            {
              "title": "Repository",
              "value": "{{.app.spec.source.repoURL}}",
              "short": true
            },
            {
              "title": "Revision",
              "value": "{{.app.status.sync.revision}}",
              "short": true
            }
            {{range $index, $c := .app.status.conditions}}
            {{if not $index}},{{end}}
            {{if $index}},{{end}}
            {
              "title": "{{$c.type}}",
              "value": "{{$c.message}}",
              "short": true
            }
            {{end}}
            ]
          }]
      teams:
        themeColor: "#80eb34"
        facts: |
          [{
            "name": "Sync Status",
            "value": "{{.app.status.sync.status}}"
          },
          {
            "name": "Repository",
            "value": "{{.app.spec.source.repoURL}}"
          },
          {
            "name": "Revision",
            "value": "{{.app.status.sync.revision}}"
          }
          {{range $index, $c := .app.status.conditions}}
            {{if not $index}},{{end}}
            {{if $index}},{{end}}
            {
              "name": "{{$c.type}}",
              "value": "{{$c.message}}",
            }
          {{end}}
          ]
        potentialAction: |-
          [{
            "@type":"OpenUri",
            "name":"Operation Application",
            "targets":[{
              "os":"default",
              "uri":"{{.context.argocdUrl}}/applications/{{.app.metadata.name}}"
            }]
          },
          {
            "@type":"OpenUri",
            "name":"Open Repository",
            "targets":[{
              "os":"default",
              "uri":"{{.app.spec.source.repoURL | call .repo.RepoURLToHTTPS}}"
            }]
          }]
        title: New version of an application {{.app.metadata.name}} is up and running.
    template.app-health-degraded: |
      email:
        subject: Application {{.app.metadata.name}} has degraded.
      message: |
        {{if eq .serviceType "slack"}}:exclamation:{{end}} Application {{.app.metadata.name}} has degraded.
        Application details: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}.
      slack:
        attachments: |
          [{
            "title": "{{ .app.metadata.name}}",
            "title_link": "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
            "color": "#f4c030",
            "fields": [
            {
              "title": "Sync Status",
              "value": "{{.app.status.sync.status}}",
              "short": true
            },
            {
              "title": "Repository",
              "value": "{{.app.spec.source.repoURL}}",
              "short": true
            }
            {{range $index, $c := .app.status.conditions}}
            {{if not $index}},{{end}}
            {{if $index}},{{end}}
            {
              "title": "{{$c.type}}",
              "value": "{{$c.message}}",
              "short": true
            }
            {{end}}
            ]
          }]
      teams:
        themeColor: "#948c73"
        facts: |
          [{
            "name": "Sync Status",
            "value": "{{.app.status.sync.status}}"
          },
          {
            "name": "Repository",
            "value": "{{.app.spec.source.repoURL}}"
          }
          {{range $index, $c := .app.status.conditions}}
            {{if not $index}},{{end}}
            {{if $index}},{{end}}
            {
              "name": "{{$c.type}}",
              "value": "{{$c.message}}",
            }
          {{end}}
          ]
        potentialAction: |
          [{
            "@type":"OpenUri",
            "name":"Open Application",
            "targets":[{
              "os":"default",
              "uri":"{{.context.argocdUrl}}/applications/{{.app.metadata.name}}"
            }]
          },
          {
            "@type":"OpenUri",
            "name":"Open Repository",
            "targets":[{
              "os":"default",
              "uri":"{{.app.spec.source.repoURL | call .repo.RepoURLToHTTPS}}"
            }]
          }]
        title: Application {{.app.metadata.name}} has degraded.
    template.app-sync-failed: |
      email:
        subject: Failed to sync application {{.app.metadata.name}}.
      message: |
        {{if eq .serviceType "slack"}}:exclamation:{{end}}  The sync operation of application {{.app.metadata.name}} has failed at {{.app.status.operationState.finishedAt}} with the following error: {{.app.status.operationState.message}}
        Sync operation details are available at: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true .
      slack:
        attachments: |
          [{
            "title": "{{ .app.metadata.name}}",
            "title_link":"{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
            "color": "#E96D76",
            "fields": [
            {
              "title": "Sync Status",
              "value": "{{.app.status.sync.status}}",
              "short": true
            },
            {
              "title": "Repository",
              "value": "{{.app.spec.source.repoURL}}",
              "short": true
            }
            {{range $index, $c := .app.status.conditions}}
            {{if not $index}},{{end}}
            {{if $index}},{{end}}
            {
              "title": "{{$c.type}}",
              "value": "{{$c.message}}",
              "short": true
            }
            {{end}}
            ]
          }]
      teams:
        themeColor: "#f70505"
        facts: |
          [{
            "name": "Sync Status",
            "value": "{{.app.status.sync.status}}"
          },
          {
            "name": "Failed at",
            "value": "{{.app.status.operationState.finishedAt}}"
          },
          {
            "name": "Repository",
            "value": "{{.app.spec.source.repoURL}}"
          }
          {{range $index, $c := .app.status.conditions}}
            {{if not $index}},{{end}}
            {{if $index}},{{end}}
            {
              "name": "{{$c.type}}",
              "value": "{{$c.message}}",
            }
          {{end}}
          ]
        potentialAction: |-
          [{
            "@type":"OpenUri",
            "name":"Open Operation",
            "targets":[{
              "os":"default",
              "uri":"{{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true"
            }]
          },
          {
            "@type":"OpenUri",
            "name":"Open Repository",
            "targets":[{
              "os":"default",
              "uri":"{{.app.spec.source.repoURL | call .repo.RepoURLToHTTPS}}"
            }]
          }]
        title: Failed to sync application {{.app.metadata.name}}.
    template.app-sync-running: |
      email:
        subject: Start syncing application {{.app.metadata.name}}.
      message: |
        The sync operation of application {{.app.metadata.name}} has started at {{.app.status.operationState.startedAt}}.
        Sync operation details are available at: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true .
      slack:
        attachments: |
          [{
            "title": "{{ .app.metadata.name}}",
            "title_link":"{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
            "color": "#0DADEA",
            "fields": [
            {
              "title": "Sync Status",
              "value": "{{.app.status.sync.status}}",
              "short": true
            },
            {
              "title": "Repository",
              "value": "{{.app.spec.source.repoURL}}",
              "short": true
            }
            {{range $index, $c := .app.status.conditions}}
            {{if not $index}},{{end}}
            {{if $index}},{{end}}
            {
              "title": "{{$c.type}}",
              "value": "{{$c.message}}",
              "short": true
            }
            {{end}}
            ]
          }]
      teams:
        themeColor: "#058ef7"
        facts: |
          [{
            "name": "Sync Status",
            "value": "{{.app.status.sync.status}}"
          },
          {
            "name": "Started at",
            "value": "{{.app.status.operationState.startedAt}}"
          },
          {
            "name": "Repository",
            "value": "{{.app.spec.source.repoURL}}"
          }
          {{range $index, $c := .app.status.conditions}}
            {{if not $index}},{{end}}
            {{if $index}},{{end}}
            {
              "name": "{{$c.type}}",
              "value": "{{$c.message}}",
            }
          {{end}}
          ]
        potentialAction: |-
          [{
            "@type":"OpenUri",
            "name":"Open Operation",
            "targets":[{
              "os":"default",
              "uri":"{{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true"
            }]
          },
          {
            "@type":"OpenUri",
            "name":"Open Repository",
            "targets":[{
              "os":"default",
              "uri":"{{.app.spec.source.repoURL | call .repo.RepoURLToHTTPS}}"
            }]
          }]
        title: Start syncing application {{.app.metadata.name}}.
    template.app-sync-status-unknown: |
      email:
        subject: Application {{.app.metadata.name}} sync status is 'Unknown'
      message: |
        {{if eq .serviceType "slack"}}:exclamation:{{end}} Application {{.app.metadata.name}} sync is 'Unknown'.
        Application details: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}.
        {{if ne .serviceType "slack"}}
        {{range $c := .app.status.conditions}}
            * {{$c.message}}
        {{end}}
        {{end}}
      slack:
        attachments: |
          [{
            "title": "{{ .app.metadata.name}}",
            "title_link":"{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
            "color": "#E96D76",
            "fields": [
            {
              "title": "Sync Status",
              "value": "{{.app.status.sync.status}}",
              "short": true
            },
            {
              "title": "Repository",
              "value": "{{.app.spec.source.repoURL}}",
              "short": true
            }
            {{range $index, $c := .app.status.conditions}}
            {{if not $index}},{{end}}
            {{if $index}},{{end}}
            {
              "title": "{{$c.type}}",
              "value": "{{$c.message}}",
              "short": true
            }
            {{end}}
            ]
          }]
      teams:
        themeColor: "#768579"
        facts: |
          [{
            "name": "Sync Status",
            "value": "{{.app.status.sync.status}}"
          },
          {
            "name": "Repository",
            "value": "{{.app.spec.source.repoURL}}"
          }
          {{range $index, $c := .app.status.conditions}}
            {{if not $index}},{{end}}
            {{if $index}},{{end}}
            {
              "name": "{{$c.type}}",
              "value": "{{$c.message}}",
            }
          {{end}}
          ]
        potentialAction: |-
          [{
            "@type":"OpenUri",
            "name":"Open Application",
            "targets":[{
              "os":"default",
              "uri":"{{.context.argocdUrl}}/applications/{{.app.metadata.name}}"
            }]
          },
          {
            "@type":"OpenUri",
            "name":"Open Repository",
            "targets":[{
              "os":"default",
              "uri":"{{.app.spec.source.repoURL | call .repo.RepoURLToHTTPS}}"
            }]
          }]
        title: Application {{.app.metadata.name}} sync status is 'Unknown'
    template.app-sync-succeeded: |
      email:
        subject: Application {{.app.metadata.name}} has been successfully synced.
      message: |
        {{if eq .serviceType "slack"}}:white_check_mark:{{end}} Application {{.app.metadata.name}} has been successfully synced at {{.app.status.operationState.finishedAt}}.
        Sync operation details are available at: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true .
      slack:
        attachments: |
          [{
            "title": "{{ .app.metadata.name}}",
            "title_link":"{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
            "color": "#18be52",
            "fields": [
            {
              "title": "Sync Status",
              "value": "{{.app.status.sync.status}}",
              "short": true
            },
            {
              "title": "Repository",
              "value": "{{.app.spec.source.repoURL}}",
              "short": true
            }
            {{range $index, $c := .app.status.conditions}}
            {{if not $index}},{{end}}
            {{if $index}},{{end}}
            {
              "title": "{{$c.type}}",
              "value": "{{$c.message}}",
              "short": true
            }
            {{end}}
            ]
          }]
      teams:
        themeColor: "#80eb34"
        facts: |
          [{
            "name": "Sync Status",
            "value": "{{.app.status.sync.status}}"
          },
          {
            "name": "Synced at",
            "value": "{{.app.status.operationState.finishedAt}}"
          },
          {
            "name": "Repository",
            "value": "{{.app.spec.source.repoURL}}"
          }
          {{range $index, $c := .app.status.conditions}}
            {{if not $index}},{{end}}
            {{if $index}},{{end}}
            {
              "name": "{{$c.type}}",
              "value": "{{$c.message}}",
            }
          {{end}}
          ]
        potentialAction: |-
          [{
            "@type":"OpenUri",
            "name":"Operation Details",
            "targets":[{
              "os":"default",
              "uri":"{{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true"
            }]
          },
          {
            "@type":"OpenUri",
            "name":"Open Repository",
            "targets":[{
              "os":"default",
              "uri":"{{.app.spec.source.repoURL | call .repo.RepoURLToHTTPS}}"
            }]
          }]
        title: Application {{.app.metadata.name}} has been successfully synced

    template.github-commit-status: |
      webhook:
        github:
          method: POST
          path: /repos/{{call .repo.FullNameByRepoURL .app.spec.source.repoURL}}/statuses/{{.app.status.operationState.operation.sync.revision}}
          body: |
            {
              {{if eq .app.status.operationState.phase "Running"}} "state": "pending"{{end}}
              {{if eq .app.status.operationState.phase "Succeeded"}} "state": "success"{{end}}
              {{if eq .app.status.operationState.phase "Error"}} "state": "error"{{end}}
              {{if eq .app.status.operationState.phase "Failed"}} "state": "error"{{end}},
              "description": "ArgoCD",
              "target_url": "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
              "context": "continuous-delivery/{{.app.metadata.name}}"
            }